# ------------------------------------------
# SPDX-License-Identifier: MIT OR Apache-2.0
# -------------------------------- 𝒒𝒑𝒓𝒐𝒋 --
[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

# Linux builds
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    # Nightly
    "-Zshare-generics=y",
    "-Zthreads=0",
    "-Clink-arg=-fuse-ld=mold",
]
